#!/usr/bin/env bash
SCRIPT_DIR="$( cd -- "$( dirname -- "$(realpath "${BASH_SOURCE[0]}")" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/venv/bin/activate"
"$SCRIPT_DIR/venv/bin/python" "$SCRIPT_DIR/cf-dns-tool.py" "$@"
